import React, { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import styles from './MarketPulse.module.css';
import SignalCard from '../SignalCard/SignalCard';

function formatRelativeTime(dateStr) {
    if (!dateStr) return null;
    const diff = Math.floor((Date.now() - new Date(dateStr).getTime()) / 1000);
    if (diff < 10) return 'just now';
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return `${Math.floor(diff / 86400)}d ago`;
}

const MarketPulse = ({ signals = [], loading = false, cachedAt = null, onRefresh, source = 'generated', generationMs = null }) => {
    const navigate = useNavigate();
    const relativeTime = useMemo(() => formatRelativeTime(cachedAt), [cachedAt]);

    const handleActionClick = (route) => {
        if (route) navigate(route);
    };

    return (
        <div className={styles.panel}>
            {/* Header */}
            <div className={styles.header}>
                <div className={styles.headerLeft}>
                    <div className={styles.titleRow}>
                        <span className={styles.title}>📈 Market Pulse</span>
                        {source === 'cache' ? (
                            <span
                                className={`${styles.sourceBadge} ${styles.cached}`}
                                title="Served from Redis in <50ms"
                            >
                                ⚡ Cached
                            </span>
                        ) : (
                            <span
                                className={`${styles.sourceBadge} ${styles.generated}`}
                                title={generationMs ? `Generated by AI in ${(generationMs / 1000).toFixed(1)}s` : 'Generated by AI'}
                            >
                                🤖 Generated
                            </span>
                        )}
                    </div>
                    {relativeTime && (
                        <span className={styles.timestamp}>Updated {relativeTime}</span>
                    )}
                </div>
                <button
                    className={`${styles.refreshBtn} ${loading ? styles.spinning : ''}`}
                    onClick={onRefresh}
                    disabled={loading}
                    title="Refresh market signals"
                    aria-label="Refresh market signals"
                >
                    ↻
                </button>
            </div>

            {/* Content */}
            {loading ? (
                <div className={styles.grid}>
                    {[0, 1, 2, 3].map(i => (
                        <div key={i} className={styles.skeleton} />
                    ))}
                </div>
            ) : signals.length === 0 ? (
                <div className={styles.empty}>
                    <p className={styles.emptyTitle}>Market data unavailable</p>
                    <p className={styles.emptySubtext}>Signals will appear when job data loads</p>
                </div>
            ) : (
                <div className={styles.grid}>
                    {signals.map((signal, index) => (
                        <SignalCard
                            key={index}
                            signal={signal}
                            index={index}
                            onActionClick={handleActionClick}
                        />
                    ))}
                </div>
            )}
        </div>
    );
};

export default MarketPulse;
